#!/bin/bash
set -e

cat > .env <<EOF
EXPO_PUBLIC_SUPABASE_URL=${EXPO_PUBLIC_SUPABASE_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${EXPO_PUBLIC_SUPABASE_ANON_KEY}
EXPO_PUBLIC_QUIZ_CSV_URL=${EXPO_PUBLIC_QUIZ_CSV_URL}
EXPO_PUBLIC_MENU_CSV_URL=${EXPO_PUBLIC_MENU_CSV_URL}
EOF

npx expo export -p web
